### ISSUE TITLE
Option to change CSV separator

### ISSUE THREAD

**Issue by gianlucascoccia** [narimiran/tably#5]
As the title states, it would be pretty useful for some countries where generally a different character is used as fields separator (here in Italy we use a semicolon for instance)

**Comment by narimiran** [comment]
I agree this would be useful.

I'll try to implement this as soon as possible.

**Comment by narimiran** [comment]
Commit 2984374 solves this by implementing new `-s` (`--sep`) argument. (Previously `-s` was `--skip`, which is now `-k`).

I tested it and it seems to work as it should, but if you find any bug please let me know.
